variables:
  NO_DOCKER: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - test
  - build_packages
  - distribute

#before_script:
#  - earthly bootstrap

test_amd64:
  stage: test
  image: earthly/earthly:v0.6.30
  only:
    - main
    - merge_requests
  tags:
    - build-server
  script:
    - earthly bootstrap
    - earthly --ci +unit-tests-linux-amd64
  when: manual

package_amd64_deb:
  stage: build_packages
  only:
    - stable
  tags:
    - build-amd64-deb
  script:
    - earthly bootstrap
    - earthly +package-linux-amd64-deb
    - /home/gitlab-runner/scp-to-orchestrator.sh

package_arm64_deb:
  stage: build_packages
  only:
    - stable
  tags:
    - build-arm64-deb
  script:
    - earthly bootstrap
    - earthly +package-linux-arm64-deb
    - /home/gitlab-runner/scp-to-orchestrator.sh

package_amd64_rpm:
  stage: build_packages
  only:
    - stable
  tags:
    - build-amd64-rpm
  script:
    - earthly bootstrap
    - earthly +package-linux-amd64-rpm
    - /home/gitlab-runner/scp-to-orchestrator.sh

build_repositories:
  stage: distribute
  only:
    - stable
  tags:
    - build-orchestration
  script:
    - /home/gitlab-runner/distribute-packages.sh

deploy_repos:
  stage: distribute
  only:
    - stable
  needs:
    - build_repositories
  tags: 
    - repo-server
  script: 
    - /home/gitlab-runner/deploy-repo.sh
