variables:
  NO_DOCKER: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - test
  - distribute

#before_script:
#  - earthly bootstrap

test_amd64:
  stage: test
  image: earthly/earthly:v0.6.30
  only:
    - main
    - merge_requests
  tags:
    - build-server
  script:
    - earthly bootstrap
    - earthly --ci +unit-tests-linux-amd64
  when: manual

package:
  stage: distribute
  only:
    - stable
  tags:
    - build-server
  script:
    - earthly bootstrap
    - earthly +package-linux-amd64-deb
    - earthly +package-linux-arm64-deb
    - earthly +package-linux-amd64-rpm
    - /home/gitlab-runner/distribute-packages.sh

deploy_repos:
  stage: distribute
  only:
    - stable
  needs:
    - package
  tags: 
    - repo-server
  script: 
    - /home/gitlab-runner/deploy-repo.sh
