variables:
  NO_DOCKER: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  #- prepare
  #- test
  #- build_packages
  - release
  - distribute



build_repositories:
  stage: distribute
  #needs:
  #  - publish_python
  tags:
    - build-orchestration
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp scripts/cicd/build-orchestration/rpm-repo-building/Dockerfile ~/rpm-build-container
    - cp scripts/cicd/build-orchestration/rpm-repo-building/repobuild.sh ~/rpm-build-container
    - cp scripts/cicd/build-orchestration/generate-stable-release.sh ~
    - bash scripts/cicd/build-orchestration/distribute-stable-packages.sh
  rules:
    - if: '$CI_COMMIT_TAG =~ /v\d.+/'

deploy_repos:
  stage: distribute
  needs:
    - build_repositories
  tags: 
    - repo-server
  script: 
    - bash scripts/cicd/repo-server/deploy-repo.sh
  rules:
    - if: '$CI_COMMIT_TAG =~ /v\d.+/'



