[workspace]
members = [
    "veilid-tools",
    "veilid-core",
    "veilid-server",
    "veilid-cli",
    "veilid-flutter/rust",
    "veilid-wasm",
]
exclude = [ "./external" ]

[patch.crates-io]
cursive = { path = "./external/cursive/cursive" }
cursive_core = { path = "./external/cursive/cursive-core" }

[profile.release]
opt-level = "s"
lto = true

[profile.dev.package.backtrace]
opt-level = 3