[workspace]
members = [
    "veilid-tools",
    "veilid-core",
    "veilid-server",
    "veilid-cli",
    "veilid-flutter/rust",
    "veilid-wasm",
]
exclude = ["./external"]

[patch.crates-io]
cursive = { version = "0.20.0", git = "https://gitlab.com/veilid/cursive.git", rev = "631dad18f0b4b246914998e8952da8abb6093bd2" }
cursive_core = { version = "0.3.7", git = "https://gitlab.com/veilid/cursive.git", rev = "631dad18f0b4b246914998e8952da8abb6093bd2" }

[profile.release]
opt-level = "s"
lto = true

[profile.dev.package.backtrace]
opt-level = 3
